### PR TITLE
uniforms

### PR DESCRIPTION
**Pull request by r58Playz**
So far (taken from MC ogl command list): 
- [x] glGetUniformLocation
- [x] glUniform1i
- [x] glUniformMatrix4fv
- [x] glUniform4fv
- [x] glUniform1fv

### CODE REVIEW

**Review by darkaegisagain — APPROVED** [review]
You should probably create a new test for this in main.cpp so if there are any regressions on glGetUniformBlockIndex they are not missed.

But it looks like you have the spirv_resources_list search method figured out.

**Comment by r58Playz** [comment]
> You should probably create a new test for this in main.cpp so if there are any regressions on glGetUniformBlockIndex they are not missed.
> 
> But it looks like you have the spirv_resources_list search method figured out.

Global uniforms for some reason are not included in the spirv list. Need to figure that one out

**Comment by r58Playz** [comment]
@darkaegisagain is this correct?

For some reason the buffer is always null.
```
void mglUniform1i(GLMContext ctx, GLint location, GLint v0)
{
    Program* ptr = ctx->state.program;
    
    ERROR_CHECK_RETURN(ptr, GL_INVALID_OPERATION)
    
    Buffer *buf = ctx->state.buffer_base[SPVC_RESOURCE_TYPE_UNIFORM_BUFFER].buffers[location].buf;

    if(buf == NULL)
    {
        ERROR_RETURN(GL_INVALID_OPERATION);
    }
    initBufferData(ctx, buf, sizeof v0, &v0);
}
```

**Comment by darkaegisagain** [comment]
You would have to start by checking where

    Buffer *buf = ctx->state.buffer_base[SPVC_RESOURCE_TYPE_UNIFORM_BUFFER].buffers[location].buf;
Is assigned…

Mike

**Comment by r58Playz** [comment]
> 

Got over that obstacle, but now the logs are getting spammed.

```
GL Error func: -[MGLRenderer mapGLBuffersToMTLBufferMap:stage:] type: 1282
failure -[MGLRenderer processGLState:]:2446
failure -[MGLRenderer mtlDrawArrays:mode:first:count:]:3354
GL Error func: -[MGLRenderer mapGLBuffersToMTLBufferMap:stage:] type: 1282
failure -[MGLRenderer processGLState:]:2446
failure -[MGLRenderer mtlDrawArrays:mode:first:count:]:3354
GL Error func: -[MGLRenderer mapGLBuffersToMTLBufferMap:stage:] type: 1282
failure -[MGLRenderer processGLState:]:2446
failure -[MGLRenderer mtlDrawArrays:mode:first:count:]:3354
```

**Comment by r58Playz** [comment]
Uniforms work now. simple fix: used the wrong array index (had to use `_UNIFORM_BUFFER` instead of `SPVC_RESOURCE_TYPE_UNIFORM_BUFFER`)

`test_draw_arrays`
Screen Shot 2022-08-20 at 1 36 24 PM
`test_draw_arrays_uniform`
Screen Shot 2022-08-20 at 1 36 59 PM

**Comment by r58Playz** [comment]
Now all I have to do is figure out global uniforms... why is it not in the list...

**Comment by darkaegisagain** [comment]
Doh…

Good job, glad to see you figured it out.

Mike

**Comment by r58Playz** [comment]
Screen Shot 2022-08-20 at 8 20 55 PM

shader:
```
    #version 450 core\n
    layout(location = 0) in vec3 position;\n
    layout(location = 1) uniform int mp = 1;\n
    void main() {\n
      gl_Position = vec4(position*mp, 1.0);\n
    }
```

**Comment by r58Playz** [comment]
I am really stumped on this one. Somehow a uniform constant buffer is getting deallocated and causing an EXC_BAD_ACCESS.

I narrowed it down to this code that sets the buffer for uniform constants.
```
    if(buf == NULL)
    {
        ctx->state.buffer_base[_UNIFORM_CONSTANT].buffers[location].buf = newBuffer(ctx, GL_UNIFORM_BUFFER, location);
        buf = ctx->state.buffer_base[_UNIFORM_CONSTANT].buffers[location].buf;
    }
```

Without API Validation:
Screen Shot 2022-08-21 at 10 05 56 AM

With API Validation:
```
-[MTLDebugRenderCommandEncoder setVertexBuffer:offset:atIndex:]:1683: failed assertion `Set Vertex Buffer Validation
buffer is not a MTLBuffer.
```

**Comment by conversy** [comment]
> Global uniforms for some reason are not included in the spirv list. Need to figure that one out

Hi @r58Playz , this makes me think of a note I have in my [wiki](https://github.com/conversy/MGL/wiki):
* there is no support for single global uniforms, you must use UBOs. This is a limitation of the glslang compiler, there is an option to support them, but I could not make it work, supposedly vulkan only (see [GL_EXT_vulkan_glsl_relaxed](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt) extension)

Could it be related to this problem?

**Comment by r58Playz** [comment]
> > Global uniforms for some reason are not included in the spirv list. Need to figure that one out
> 
> Hi @r58Playz , this makes me think of a note I have in my [wiki](https://github.com/conversy/MGL/wiki):
> 
>     * there is no support for single global uniforms, you must use UBOs. This is a limitation of the glslang compiler, there is an option to support them, but I could not make it work, supposedly vulkan only (see [GL_EXT_vulkan_glsl_relaxed](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt) extension)
> 
> 
> Could it be related to this problem?

Technically the glslang compiler has support for single global uniforms, it even passes it on to the MSL compiler, but the MSL compiler wasn't sending it as part of the spirv resource list. I added that in https://github.com/r58Playz/SPIRV-Cross/tree/uniform-constants.

**Comment by r58Playz** [comment]
Fixed (had to set the mtl data to null every time i dealloc)


https://user-images.githubusercontent.com/45221816/187114460-934af601-fc81-4261-8a81-5d255553e5ab.mov

**Pull request merged**
