### PR TITLE
Makefile: make it more general and customizable

### PR DESCRIPTION
**Pull request by conversy**
I was able to run the test on my M1/Monterey with the following mods.

### CODE REVIEW

**Comment by douira** [comment]
When I try to run the make build it fails with the following error:
```
Consolidate compiler generated dependencies of target glfw
[ 23%] Built target glfw
Consolidate compiler generated dependencies of target boing
[ 24%] Linking C executable boing.app/Contents/MacOS/boing
```
Also I've noticed that the `clone_external` and `build_external` scripts don't actually build all the items that are listed in the README. In particular, `glm` is not cloned or built.

**Comment by conversy** [comment]
please do not use the cmake stuff from glfw. In MGL/, a simple 'make -j test' should compile mgl, glfw and the test.

**Comment by douira** [comment]
I've run the two commands you supplied on a new clone of your MGL fork. It successfully executes `make install-pkgdeps` but then `make -j test` results in the following errors: (I didn't do any of the external build stuff, just the two make commands)
```
c++ -std=c++14 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -Iglfw/include -c test_mgl_glfw/main.cpp -o build/test_mgl_glfw/main.o
cc -std=gnu17 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -D_GLFW_COCOA -c glfw/src/cocoa_time.c -o build/glfw/src/cocoa_time.o
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' [-Wmissing-sysroot]
test_mgl_glfw/main.cpp:21:10: fatal error: 'mach/mach_vm.h' file not found
#include <mach/mach_vm.h>
         ^~~~~~~~~~~~~~~~
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' [-Wmissing-sysroot]
cc -std=gnu17 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -D_GLFW_COCOA -c glfw/src/posix_module.c -o build/glfw/src/posix_module.o
cc -std=gnu17 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -D_GLFW_COCOA -c glfw/src/posix_thread.c -o build/glfw/src/posix_thread.o
In file included from glfw/src/cocoa_time.c:29:
In file included from glfw/src/internal.h:331:
In file included from glfw/src/platform.h:42:
glfw/src/cocoa_platform.h:29:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' [-Wmissing-sysroot]
make: *** [build/glfw/src/cocoa_time.o] Error 1
make: *** Waiting for unfinished jobs....
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk' [-Wmissing-sysroot]
In file included from glfw/src/posix_module.c:29:
In file included from glfw/src/internal.h:331:
In file included from glfw/src/platform.h:42:
glfw/src/cocoa_platform.h:29:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
In file included from glfw/src/posix_thread.c:30:
In file included from glfw/src/internal.h:331:
In file included from glfw/src/platform.h:42:
glfw/src/cocoa_platform.h:29:10: fatal error: 'Carbon/Carbon.h' file not found
#include <Carbon/Carbon.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/glfw/src/posix_module.o] Error 1
1 error generated.
make: *** [build/glfw/src/posix_thread.o] Error 1
1 error generated.
make: *** [build/test_mgl_glfw/main.o] Error 1
make: *** wait: No child processes.  Stop.
```
Is this possibly the result of a macOS version mismatch? It seems to be looking for something called `MacOSX11.1.sdk` but I'm on macOS 11.6 currently. (I do have XCode installed) Also, brew reports that the installed packages are not linked, is that a problem?

**Comment by douira** [comment]
I've tried symlinking `MacOSX11.1.sdk` to `MacOSX.sdk` which changed the error to this:
```
...
cc -std=gnu17 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -c MGL/src/buffers.c -o build/MGL/src/buffers.o
1 error generated.
cc -std=gnu17 -MMD -gfull -Og -arch x86_64 -I/usr/local/include -I/usr/local/include/spirv -I/usr/local/include/spirv/1.2 -Iexternal/SPIRV-Cross -I/usr/local/opt/glslang/include/glslang/Include -I/usr/local/include  -I/usr/local/include -I/usr/local/Cellar/glm/0.9.9.8/include -IMGL/include -IMGL/SPIRV/SPIRV-Cross -DENABLE_OPT=0 -DSPIRV_CROSS_C_API_MSL=1 -DSPIRV_CROSS_C_API_GLSL=1 -DSPIRV_CROSS_C_API_CPP=1 -DSPIRV_CROSS_C_API_REFLECT=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -c MGL/src/compute.c -o build/MGL/src/compute.o
make: *** [build/test_mgl_glfw/main.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from MGL/src/compute.c:21:
In file included from MGL/include/glm_context.h:27:
In file included from MGL/include/glm_dispatch.h:13:
/usr/local/include/GL/glcorearb.h:63:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
In file included from MGL/src/buffers.c:26:
In file included from MGL/include/glm_context.h:27:
In file included from MGL/include/glm_dispatch.h:13:
/usr/local/include/GL/glcorearb.h:63:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/MGL/src/compute.o] Error 1
1 error generated.
make: *** [build/MGL/src/buffers.o] Error 1
```

Probably because the SDK is wrong now even though it exists?

**Comment by conversy** [comment]
for the error related to the SDK, please make sure the line that defines SDK_ROOT is uncommented.
for <KHR/khrplatform.h>, I have them presumably because I have already installed mesa with brew.
Please try 'brew install mesa' and make again.

**Comment by douira** [comment]
Thanks for the hints! I have installed mesa with brew and uncommented that line. The error is again different. Running `make -j test` results in the following error:
```
test_mgl_glfw/main.cpp:36:10: fatal error: 'GL/utils.h' file not found
#include <GL/utils.h>
         ^~~~~~~~~~~~
```
Otherwise the build process seems to be working.

**Comment by darkaegisagain** [comment]
I will take a look at the #include <GL/utils.h> issue, the Xcode build automatically copies headers to /usr/local/include/GL

**Comment by conversy** [comment]
GL/utils.h is not really needed.
I commented it out and add those two defines line 278:
```
#define MIN(a,b) ((a)<(b)?(a):(b))
#define MAX(a,b) ((a)>(b)?(a):(b))
```

I might push this change later, or Mike may provide a better solution?

**Comment by darkaegisagain** [comment]
Sure take it out, as long as it builds. I added macros or local definitions
of external functions here and there to avoid adding too many dependencies
on include files.

A lot of this was just to get it up and running... so it's a bit crusty on
the edges.

Mike


"*The* difference between communism and *socialism* is that under
*socialism* central planning *ends* with *a* *gun* in your face, whereas
under communism central planning begins with a *gun* in your face." ― Kevin
D. Williamson

**Comment by douira** [comment]
> GL/utils.h is not really needed. I commented it out and add those two defines line 278:
> 
> ```
> #define MIN(a,b) ((a)<(b)?(a):(b))
> #define MAX(a,b) ((a)>(b)?(a):(b))
> ```
> 
> I might push this change later, or Mike may provide a better solution?

I've applied these changes locally and tried to build it with `make -j test`. The following error is produced:
```
In file included from MGL/src/program.c:26:
MGL/SPIRV/SPIRV-Cross/spirv_cross_c.h:28:10: fatal error: 'spirv.h' file not found
#include "spirv.h"
         ^~~~~~~~~
```
It seems another include file can't be found, even though this is probably (?) something that should be present _somewhere_ on my system because `make install-pkgdeps` was run beforehand.

**Comment by conversy** [comment]
if you used `make install-pkgdeps`, then `config.mk` should contain this:

```
spirv_headers_path := ../SPIRV-Headers/include/spirv/1.2
spirv_cross_include_path := ../SPIRV-Cross
spirv_cross_lib_path := ../SPIRV-Cross/build
```

**Comment by douira** [comment]
Oh, thanks for the help! That worked, it's rendering the checkerboard now! There's quite a lot of configuration that goes into this (and I'm entirely inexperienced with building C-things) but it worked with your help.

**Comment by darkaegisagain** [comment]
I like the idea of a Makefile but for now I would recommend using the
MGL xcode project, just build it as a new target and use test_mgl_glfw as
an example. This way you can see any asserts or errors built in.

We used Makefile builds and emacs / gdb for years at Apple until llvm
shipped and we ended up with lldb so most of us internally switched to
building the OpenGL framework as an Xcode external build and debugged it in
Xcode (I loved Project builder.. it was so much better).

For release builds Makefiles make perfect sense, but for me I am sticking
with the Xcode build until the project matures a bit more.

The default error handler issues an assert rather than allowing error
checking through GL.. its real debug code but its more useful for
developing the API at this point. You can disable this by defining a
different error handler in the glm context code.

Mike



"*The* difference between communism and *socialism* is that under
*socialism* central planning *ends* with *a* *gun* in your face, whereas
under communism central planning begins with a *gun* in your face." ― Kevin
D. Williamson

**Pull request merged**
